package com.javaweb.model;
// Generated Dec 5, 2016 9:49:39 AM by Hibernate Tools 4.3.1



/**
 * Ctgiohang generated by hbm2java
 */
public class Ctgiohang  implements java.io.Serializable {


     private Integer machitiet;
     private int soluong;
     private double thanhtien;
     private int masanpham;
     private int magiohang;

    public Ctgiohang() {
    }

    public Ctgiohang(int soluong, double thanhtien, int masanpham, int magiohang) {
       this.soluong = soluong;
       this.thanhtien = thanhtien;
       this.masanpham = masanpham;
       this.magiohang = magiohang;
    }
   
    public Integer getMachitiet() {
        return this.machitiet;
    }
    
    public void setMachitiet(Integer machitiet) {
        this.machitiet = machitiet;
    }
    public int getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(int soluong) {
        this.soluong = soluong;
    }
    public double getThanhtien() {
        return this.thanhtien;
    }
    
    public void setThanhtien(double thanhtien) {
        this.thanhtien = thanhtien;
    }
    public int getMasanpham() {
        return this.masanpham;
    }
    
    public void setMasanpham(int masanpham) {
        this.masanpham = masanpham;
    }
    public int getMagiohang() {
        return this.magiohang;
    }
    
    public void setMagiohang(int magiohang) {
        this.magiohang = magiohang;
    }




}


