package com.javaweb.model;
// Generated Dec 5, 2016 9:49:39 AM by Hibernate Tools 4.3.1



/**
 * Giohang generated by hbm2java
 */
public class Giohang  implements java.io.Serializable {


     private Integer magiohang;
     private String tengiohang;
     private String mota;
     private int makhachhang;

    public Giohang() {
    }

    public Giohang(String tengiohang, String mota, int makhachhang) {
       this.tengiohang = tengiohang;
       this.mota = mota;
       this.makhachhang = makhachhang;
    }
   
    public Integer getMagiohang() {
        return this.magiohang;
    }
    
    public void setMagiohang(Integer magiohang) {
        this.magiohang = magiohang;
    }
    public String getTengiohang() {
        return this.tengiohang;
    }
    
    public void setTengiohang(String tengiohang) {
        this.tengiohang = tengiohang;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public int getMakhachhang() {
        return this.makhachhang;
    }
    
    public void setMakhachhang(int makhachhang) {
        this.makhachhang = makhachhang;
    }




}


