package com.javaweb.model;
// Generated Dec 5, 2016 9:49:39 AM by Hibernate Tools 4.3.1



/**
 * Gioithieu generated by hbm2java
 */
public class Gioithieu  implements java.io.Serializable {


     private Integer magt;
     private String ten;
     private String noidung;

    public Gioithieu() {
    }

    public Gioithieu(String ten, String noidung) {
       this.ten = ten;
       this.noidung = noidung;
    }
   
    public Integer getMagt() {
        return this.magt;
    }
    
    public void setMagt(Integer magt) {
        this.magt = magt;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getNoidung() {
        return this.noidung;
    }
    
    public void setNoidung(String noidung) {
        this.noidung = noidung;
    }




}


