package com.javaweb.model;
// Generated Dec 5, 2016 9:49:39 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Hoadon generated by hbm2java
 */
public class Hoadon  implements java.io.Serializable {


     private Integer mahoadon;
     private String tenhoadon;
     private Date thoigianlap;
     private double thanhtien;
     private int magiohang;

    public Hoadon() {
    }

    public Hoadon(String tenhoadon, Date thoigianlap, double thanhtien, int magiohang) {
       this.tenhoadon = tenhoadon;
       this.thoigianlap = thoigianlap;
       this.thanhtien = thanhtien;
       this.magiohang = magiohang;
    }
   
    public Integer getMahoadon() {
        return this.mahoadon;
    }
    
    public void setMahoadon(Integer mahoadon) {
        this.mahoadon = mahoadon;
    }
    public String getTenhoadon() {
        return this.tenhoadon;
    }
    
    public void setTenhoadon(String tenhoadon) {
        this.tenhoadon = tenhoadon;
    }
    public Date getThoigianlap() {
        return this.thoigianlap;
    }
    
    public void setThoigianlap(Date thoigianlap) {
        this.thoigianlap = thoigianlap;
    }
    public double getThanhtien() {
        return this.thanhtien;
    }
    
    public void setThanhtien(double thanhtien) {
        this.thanhtien = thanhtien;
    }
    public int getMagiohang() {
        return this.magiohang;
    }
    
    public void setMagiohang(int magiohang) {
        this.magiohang = magiohang;
    }




}


