package com.javaweb.model;
// Generated Dec 5, 2016 9:49:39 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Khachhang generated by hbm2java
 */
public class Khachhang  implements java.io.Serializable {


     private Integer makhachhang;
     private String username;
     private String password;
     private String fullname;
     private Date ngaysinh;
     private String diachi;
     private String sdt;
     private int maquyen;

    public Khachhang() {
    }

    public Khachhang(String username, String password, String fullname, Date ngaysinh, String diachi, String sdt, int maquyen) {
       this.username = username;
       this.password = password;
       this.fullname = fullname;
       this.ngaysinh = ngaysinh;
       this.diachi = diachi;
       this.sdt = sdt;
       this.maquyen = maquyen;
    }
   
    public Integer getMakhachhang() {
        return this.makhachhang;
    }
    
    public void setMakhachhang(Integer makhachhang) {
        this.makhachhang = makhachhang;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public Date getNgaysinh() {
        return this.ngaysinh;
    }
    
    public void setNgaysinh(Date ngaysinh) {
        this.ngaysinh = ngaysinh;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }
    public int getMaquyen() {
        return this.maquyen;
    }
    
    public void setMaquyen(int maquyen) {
        this.maquyen = maquyen;
    }




}


