package com.javaweb.model;
// Generated Dec 5, 2016 9:49:39 AM by Hibernate Tools 4.3.1



/**
 * Lienhe generated by hbm2java
 */
public class Lienhe  implements java.io.Serializable {


     private Integer malienhe;
     private String ten;
     private String email;
     private String sdt;

    public Lienhe() {
    }

    public Lienhe(String ten, String email, String sdt) {
       this.ten = ten;
       this.email = email;
       this.sdt = sdt;
    }
   
    public Integer getMalienhe() {
        return this.malienhe;
    }
    
    public void setMalienhe(Integer malienhe) {
        this.malienhe = malienhe;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }




}


