package com.javaweb.model;
// Generated Dec 5, 2016 9:49:39 AM by Hibernate Tools 4.3.1



/**
 * Loaisanpham generated by hbm2java
 */
public class Loaisanpham  implements java.io.Serializable {


     private Integer maloaisanpham;
     private String tenloai;
     private String mota;

    public Loaisanpham() {
    }

    public Loaisanpham(String tenloai, String mota) {
       this.tenloai = tenloai;
       this.mota = mota;
    }
   
    public Integer getMaloaisanpham() {
        return this.maloaisanpham;
    }
    
    public void setMaloaisanpham(Integer maloaisanpham) {
        this.maloaisanpham = maloaisanpham;
    }
    public String getTenloai() {
        return this.tenloai;
    }
    
    public void setTenloai(String tenloai) {
        this.tenloai = tenloai;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }




}


