package com.javaweb.model;
// Generated Dec 5, 2016 9:49:39 AM by Hibernate Tools 4.3.1



/**
 * Nhacc generated by hbm2java
 */
public class Nhacc  implements java.io.Serializable {


     private Integer manhacc;
     private String tennhacc;
     private String diachi;
     private String sdt;

    public Nhacc() {
    }

	
    public Nhacc(String tennhacc, String diachi) {
        this.tennhacc = tennhacc;
        this.diachi = diachi;
    }
    public Nhacc(String tennhacc, String diachi, String sdt) {
       this.tennhacc = tennhacc;
       this.diachi = diachi;
       this.sdt = sdt;
    }
   
    public Integer getManhacc() {
        return this.manhacc;
    }
    
    public void setManhacc(Integer manhacc) {
        this.manhacc = manhacc;
    }
    public String getTennhacc() {
        return this.tennhacc;
    }
    
    public void setTennhacc(String tennhacc) {
        this.tennhacc = tennhacc;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }




}


