package com.javaweb.model;
// Generated Dec 5, 2016 9:49:39 AM by Hibernate Tools 4.3.1



/**
 * Phanhoi generated by hbm2java
 */
public class Phanhoi  implements java.io.Serializable {


     private Integer maphanhoi;
     private String email;
     private String tieude;
     private String noidung;

    public Phanhoi() {
    }

    public Phanhoi(String email, String tieude, String noidung) {
       this.email = email;
       this.tieude = tieude;
       this.noidung = noidung;
    }
   
    public Integer getMaphanhoi() {
        return this.maphanhoi;
    }
    
    public void setMaphanhoi(Integer maphanhoi) {
        this.maphanhoi = maphanhoi;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTieude() {
        return this.tieude;
    }
    
    public void setTieude(String tieude) {
        this.tieude = tieude;
    }
    public String getNoidung() {
        return this.noidung;
    }
    
    public void setNoidung(String noidung) {
        this.noidung = noidung;
    }




}


