package com.javaweb.model;
// Generated Dec 5, 2016 9:49:39 AM by Hibernate Tools 4.3.1



/**
 * Quanlytrang generated by hbm2java
 */
public class Quanlytrang  implements java.io.Serializable {


     private Integer matrang;
     private String tentrang;
     private String link;
     private String mota;

    public Quanlytrang() {
    }

    public Quanlytrang(String tentrang, String link, String mota) {
       this.tentrang = tentrang;
       this.link = link;
       this.mota = mota;
    }
   
    public Integer getMatrang() {
        return this.matrang;
    }
    
    public void setMatrang(Integer matrang) {
        this.matrang = matrang;
    }
    public String getTentrang() {
        return this.tentrang;
    }
    
    public void setTentrang(String tentrang) {
        this.tentrang = tentrang;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }




}


