package com.javaweb.model;
// Generated Dec 5, 2016 9:49:39 AM by Hibernate Tools 4.3.1



/**
 * Quyen generated by hbm2java
 */
public class Quyen  implements java.io.Serializable {


     private Integer maquyen;
     private String tenquyen;
     private String mota;

    public Quyen() {
    }

    public Quyen(String tenquyen, String mota) {
       this.tenquyen = tenquyen;
       this.mota = mota;
    }
   
    public Integer getMaquyen() {
        return this.maquyen;
    }
    
    public void setMaquyen(Integer maquyen) {
        this.maquyen = maquyen;
    }
    public String getTenquyen() {
        return this.tenquyen;
    }
    
    public void setTenquyen(String tenquyen) {
        this.tenquyen = tenquyen;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }




}


