package com.javaweb.model;
// Generated Dec 5, 2016 9:49:39 AM by Hibernate Tools 4.3.1



/**
 * Sanpham generated by hbm2java
 */
public class Sanpham  implements java.io.Serializable {


     private Integer masanpham;
     private String tensanpham;
     private int soluong;
     private double gianhap;
     private double giaban;
     private String mota;
     private int maloai;
     private int manhacc;

    public Sanpham() {
    }

    public Sanpham(String tensanpham, int soluong, double gianhap, double giaban, String mota, int maloai, int manhacc) {
       this.tensanpham = tensanpham;
       this.soluong = soluong;
       this.gianhap = gianhap;
       this.giaban = giaban;
       this.mota = mota;
       this.maloai = maloai;
       this.manhacc = manhacc;
    }
   
    public Integer getMasanpham() {
        return this.masanpham;
    }
    
    public void setMasanpham(Integer masanpham) {
        this.masanpham = masanpham;
    }
    public String getTensanpham() {
        return this.tensanpham;
    }
    
    public void setTensanpham(String tensanpham) {
        this.tensanpham = tensanpham;
    }
    public int getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(int soluong) {
        this.soluong = soluong;
    }
    public double getGianhap() {
        return this.gianhap;
    }
    
    public void setGianhap(double gianhap) {
        this.gianhap = gianhap;
    }
    public double getGiaban() {
        return this.giaban;
    }
    
    public void setGiaban(double giaban) {
        this.giaban = giaban;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public int getMaloai() {
        return this.maloai;
    }
    
    public void setMaloai(int maloai) {
        this.maloai = maloai;
    }
    public int getManhacc() {
        return this.manhacc;
    }
    
    public void setManhacc(int manhacc) {
        this.manhacc = manhacc;
    }




}


